airflow:
  config:
    AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/efs/plugins
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: "False"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10
  extraVolumeMounts:
    - name: synchronised-efs
      mountPath: /opt/airflow/efs
  extraVolumes:
    - name: synchronised-efs
      hostPath:
        path: /opt/airflow/efs
logs:
  path: /opt/airflow/efs/logs
  persistence:
    enabled: false
dags:
  path: /opt/airflow/efs/dags
  doNotPickle: false
  installRequirements: false
  persistence:
    enabled: false
web:
  nodeSelector: {}
  service:
    type: NodePort
    nodePort:
      http: 30080
