kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts: 
      - containerPath: /opt/airflow/efs
        hostPath: helm_airflow_mnt
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "0.0.0.0"
networking:
  apiServerAddress: "0.0.0.0" # Note: This setup is easy but not secure.
  apiServerPort: 30443 # Optional
